export const templatePriorityIntents: string[] = [
  'contract',
  'pricing',
  'onboarding',
  'cancel',
  'industry',
  'overview',
  'function',
  'recommendation',
  'difference',
  'support',
  'login',
  'security',
  'integration',
  'compliance',
  'faq',
  'billing',
];
